version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-flights
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=lambda,apigateway,s3,dynamodb
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./infrastructure/localstack:/etc/localstack/init/ready.d"
      - "./src:/opt/code/src"
      - "./data:/opt/code/data"
      - "/var/run/docker.sock:/var/run/docker.sock"